version: '3'
services:
 db:
  image: mcr.microsoft.com/mssql/server:2022-latest
  ports: 
    - 1450:1433	
  environment:
    SA_PASSWORD: "S3cur3P@ssW0rd!"
    ACCEPT_EULA: "Y"

 portifoliowebapi:
  build: .
  ports: 
     - 8090:80
  volumes:
     - .:/code
  depends_on:
     - db

 